CREATE USER "CLV61PRD" IDENTIFIED BY CLV_61_PRD
      DEFAULT TABLESPACE "BSBIS_DATA_CLV61"
      TEMPORARY TABLESPACE "TEMP";

   GRANT "CONNECT" TO "CLV61PRD";
   GRANT "RESOURCE" TO "CLV61PRD";
   GRANT "DBA" TO "CLV61PRD";
   GRANT "IMP_FULL_DATABASE" TO "CLV61PRD";
   GRANT "DATAPUMP_EXP_FULL_DATABASE" TO "CLV61PRD";
   GRANT "DATAPUMP_IMP_FULL_DATABASE" TO "CLV61PRD";
   GRANT "SCHEDULER_ADMIN" TO "CLV61PRD";
   GRANT "SOLIFE_USER" TO "CLV61PRD";

  GRANT CREATE TYPE TO "CLV61PRD";
  GRANT CREATE PROCEDURE TO "CLV61PRD";
  GRANT CREATE DATABASE LINK TO "CLV61PRD";
  GRANT CREATE VIEW TO "CLV61PRD";
  GRANT CREATE ANY SYNONYM TO "CLV61PRD";
  GRANT UNLIMITED TABLESPACE TO "CLV61PRD";
