BEGIN
FOR aPart IN (SELECT TABLE_NAME, PARTITION_NAME 
                FROM USER_TAB_PARTITIONS 
               WHERE TABLE_NAME in ('FTF_INSP_PRICE', 'FTF_INS_INSTRUMENT') 
                 AND LAST_ANALYZED IS NULL) LOOP
    DBMS_STATS.GATHER_TABLE_STATS(USER, aPart.TABLE_NAME, aPart.PARTITION_NAME);
END LOOP;
END;