explain plan for SELECT DISTINCT o1.CID p0, o1.OID p1, o10.ENDORSEMENT_TYPE p2, o10.POLICY_NUMBER p3, o13.CALCULATION_DATE p4, o14.IDENTIFIER p5 
FROM OPERATION_TAX_DETAILS o1 
INNER JOIN ENDORSED_POLICY o10 ON o1.OWNER_OID = o10.OID 
INNER JOIN (POLICY o11 LEFT OUTER JOIN PENSION_POLICY ql_o11_3 ON o11.OID = ql_o11_3.OID AND o11.VERSION = ql_o11_3.VERSION) ON o10.POLICY_OID = o11.OID 
INNER JOIN TAX_FRAMEWORK_LINK o12 ON (o1.TAX_FRAMEWORK_LINK_OID = o12.OID) 
INNER JOIN OPE_TAX_CALCULATION_RESULT o13 ON o13.TAX_RESULT_OWNER_OID = o1.OID LEFT OUTER JOIN PROPOSITION o14 ON (o14.ENDORSED_POLICY_OID = o10.OID) 
WHERE o11.POLICY_NUMBER LIKE :1 AND o12.TAX_FRAMEWORK_ID IS NOT NULL AND ((((((((((((((((((((o10.ENDORSEMENT_TYPE = :2 ) OR (o10.ENDORSEMENT_TYPE = :3 )) OR (o10.ENDORSEMENT_TYPE = :4 )) 
OR (o10.ENDORSEMENT_TYPE = :5 )) OR (o10.ENDORSEMENT_TYPE = :6 )) OR (o10.ENDORSEMENT_TYPE = :7 )) OR (o10.ENDORSEMENT_TYPE = :8 )) OR (o10.ENDORSEMENT_TYPE = :9 )) 
OR (o10.ENDORSEMENT_TYPE = :10 )) OR (o10.ENDORSE MENT_TYPE = :11 )) OR (o10.ENDORSEMENT_TYPE = :12 )) OR (o10.ENDORSEMENT_TYPE = :13 )) 
OR (o10.ENDORSEMENT_TYPE = :14 )) OR (o10.ENDORSEMENT_TYPE = :15 )) OR (o10.ENDORSEMENT_TYPE = :16 )) OR (o10.ENDORSEMENT_TYPE = :17 )) 
OR (o10.ENDORSEMENT_TYPE = :18 )) OR (o10.ENDORSEMENT_TYPE = :19 )) OR (o10.ENDORSEMENT_TYPE = :20 )) OR (o10.ENDORSEMENT_TYPE = :21 )) 
UNION ALL SELECT DISTINCT o2.CID p0, o2.OID p1, - 1, o18.POLICY_NUMBER p2, o21.CALCULATION_DATE p3, '' FROM CLAIM_COV_TAX_DETAILS o2 
INNER JOIN CLAIMED_COVERAGE_DETAIL o15 ON o2.CLAIMED_COVERAGE_DETAIL_OID = o15.OID 
INNER JOIN (GENERIC_COVERAGE o16 LEFT OUTER JOIN RISK_COVERAGE ql_o16_1 ON o16.OID = ql_o16_1.OID AND o16.VERSION = ql_o16_1.VERSION 
                                 LEFT OUTER JOIN INVESTMENT_COVERAGE ql_o16_2 ON o16.OID = ql_o16_2.OID AND o16.VERSION = ql_o16_2.VERSION) ON o16.OID = o15.COVERAGE_IDENTIFIER 
								 INNER JOIN PRODUCT_COMPONENT_IMPL o17 ON o16.OWNER_OID = o17.OID 
								 INNER JOIN (POLICY o18 LEFT OUTER JOIN PENSION_POLICY ql_o18_3 ON o18.OID = ql _o18_3.OID AND o18.VERSION = ql_o18_3.VERSION) ON o17.POLICY_IMPL_OID = o18.OID 
								 INNER JOIN TAX_DETAILS o19 ON o19.OWNER_OID = o18.OID 
								 INNER JOIN TAX_FRAMEWORK_LINK o20 ON (o19.TAX_FRAMEWORK_LINK_OID = o20.OID) 
								 INNER JOIN CLAIM_TAX_CALCULATION_RESULT o21 ON o21.TAX_RESULT_OWNER_OID = o2.OID 
								 WHERE o18.POLICY_NUMBER LIKE :22 AND o20.TAX_FRAMEWORK_ID IS NOT NULL 
								 UNION ALL 
								 SELECT DISTINCT o3.CID p0, o3.OID p1, - 1, o25.POLICY_NUMBER p2, o28.CALCULATION_DATE p3, '' 
								 FROM CLAIM_BENEF_COV_TAX_DETAILS o3 
INNER JOIN CLAIMED_COVERAGE_DETAIL o22 ON o3.CLAIMED_COVERAGE_DETAIL_OID = o22.OID INNER JOIN (GENERIC_COVERAGE o23 
LEFT OUTER JOIN RISK_COVERAGE ql_o23_1 ON o23.OID = ql_o23_1.OID AND o23.VERSION = ql_o23_1.VERSION 
LEFT OUTER JOIN INVESTMENT_COVERAGE ql_o23_2 ON o23.OID = ql_o23_2.OID AND o23.VERSION = ql_o23_2.VERSION) ON o23.OID = o22.COVERAGE_IDENTIFIER 
INNER JOIN PRODUCT_COMPONENT_IMPL o24 ON o23.OWNER_OID = o24.OID 
INNER JOIN (POLICY o25 LEFT OUTER JOIN PENSION_POLICY ql_o25_3 ON o25 .OID = ql_o25_3.OID AND o25.VERSION = ql_o25_3.VERSION) ON o24.POLICY_IMPL_OID = o25.OID 
INNER JOIN TAX_DETAILS o26 ON o26.OWNER_OID = o25.OID 
INNER JOIN TAX_FRAMEWORK_LINK o27 ON (o26.TAX_FRAMEWORK_LINK_OID = o27.OID) 
INNER JOIN CLAIM_TAX_CALCULATION_RESULT o28 ON o28.TAX_RESULT_OWNER_OID = o3.OID 
WHERE o25.POLICY_NUMBER LIKE :23 AND o27.TAX_FRAMEWORK_ID IS NOT NULL 
UNION ALL 
SELECT DISTINCT o4.CID p0, o4.OID p1, - 1, o29.TARGET_EXTERNAL_ID p2, o31.CALCULATION_DATE p3, '' 
FROM OPERATION_TAX_DETAILS o4 
INNER JOIN BILL o29 ON o4.OWNER_OID = o29.OID 
INNER JOIN TAX_FRAMEWORK_LINK o30 ON (o4.TAX_FRAMEWORK_LINK_OID = o30.OID) 
INNER JOIN OPE_TAX_CALCULATION_RESULT o31 ON o31.TAX_RESULT_OWNER_OID = o4.OID 
WHERE o29.TARGET_EXTERNAL_ID LIKE :24 AND o30.TAX_FRAMEWORK_ID IS NOT NULL 
UNION ALL 
SELECT DISTINCT o5.CID p0, o5.OID p1, - 1, o35.POLICY_NUMBER p2, o37.CALCULATION_DATE p3, '' 
FROM OPERATION_TAX_DETAILS o5 
INNER JOIN BENEFIT_PAYMENT o32 ON o5.OWNER_OID = o32.OID 
INNER JOIN BENE FIT_FILE o33 ON o32.BENEFIT_FILE_OID = o33.OID 
INNER JOIN TECH_ENDORSEMENT_DEFINITION o34 ON (o34.BENEFIT_ORIGIN_IDENTIFIER = o33.ORIGIN_IDENTIFIER) 
INNER JOIN ENDORSED_POLICY o35 ON o34.POLICY_OID = o35.OID AND o35.CID IN (6601) 
INNER JOIN TAX_FRAMEWORK_LINK o36 ON (o5.TAX_FRAMEWORK_LINK_OID = o36.OID) 
INNER JOIN OPE_TAX_CALCULATION_RESULT o37 ON o37.TAX_RESULT_OWNER_OID = o5.OID 
WHERE o35.POLICY_NUMBER LIKE :25 AND o36.TAX_FRAMEWORK_ID IS NOT NULL AND o33.ORIGIN_TYPE IN ( :26 , :27 , :28 , :29 , :30 , :31 , :32 ) 
UNION ALL 
SELECT DISTINCT o6.CID p0, o6.OID p1, - 1, o42.POLICY_NUMBER p2, o46.CALCULATION_DATE p3, '' 
FROM OPERATION_TAX_DETAILS o6 
INNER JOIN BENEFIT_PAYMENT o38 ON o6.OWNER_OID = o38.OID 
INNER JOIN BENEFIT_FILE o39 ON o38.BENEFIT_FILE_OID = o39.OID 
INNER JOIN CLAIM o40 ON (o40.CLAIM_ID = o39.ORIGIN_IDENTIFIER) 
INNER JOIN TRAD_LIFE_CLAIM_DETAIL o41 ON o40.CLAIM_DETAIL_OID = o41.OID 
INNER JOIN CLAIMED_COVERAGE_DETAIL o42 ON o42.TRAD_LIFE_CLAIM_DETAIL_OID = o41.O ID 
INNER JOIN TAX_FRAMEWORK_LINK o43 ON (o6.TAX_FRAMEWORK_LINK_OID = o43.OID) 
INNER JOIN BENEFIT_PAYMENT o44 ON o6.OWNER_OID = o44.OID 
INNER JOIN BENEFIT_FILE o45 ON o44.BENEFIT_FILE_OID = o45.OID 
INNER JOIN OPE_TAX_CALCULATION_RESULT o46 ON o46.TAX_RESULT_OWNER_OID = o6.OID 
WHERE o42.POLICY_NUMBER LIKE :33 AND o43.TAX_FRAMEWORK_ID IS NOT NULL AND o45.ORIGIN_TYPE IN ( :34 , :35 ) 
UNION ALL 
SELECT DISTINCT o7.CID p0, o7.OID p1, - 1, o51.POLICY_NUMBER p2, o55.CALCULATION_DATE p3, '' 
FROM OPERATION_TAX_DETAILS o7 
INNER JOIN BENEFIT_PAYMENT o47 ON o7.OWNER_OID = o47.OID 
INNER JOIN BENEFIT_FILE o48 ON o47.BENEFIT_FILE_OID = o48.OID 
INNER JOIN POLICY_LOAN o49 ON (o49.ID = o48.ORIGIN_IDENTIFIER) 
INNER JOIN PRODUCT_COMPONENT_IMPL o50 ON o49.PRODUCT_COMPONENT_OID = o50.OID 
INNER JOIN (POLICY o51 LEFT OUTER JOIN PENSION_POLICY ql_o51_3 ON o51.OID = ql_o51_3.OID AND o51.VERSION = ql_o51_3.VERSION) ON o50.POLICY_IMPL_OID = o51.OID 
INNER JOIN TAX_FRAMEWORK_LINK o52 ON (o7.TAX_FRAMEWORK_LINK_ OID = o52.OID) 
INNER JOIN BENEFIT_PAYMENT o53 ON o7.OWNER_OID = o53.OID 
INNER JOIN BENEFIT_FILE o54 ON o53.BENEFIT_FILE_OID = o54.OID 
INNER JOIN OPE_TAX_CALCULATION_RESULT o55 ON o55.TAX_RESULT_OWNER_OID = o7.OID 
WHERE o51.POLICY_NUMBER LIKE :36 AND o52.TAX_FRAMEWORK_ID IS NOT NULL AND o54.ORIGIN_TYPE = :37 
UNION ALL SELECT DISTINCT o8.CID p0, o8.OID p1, - 1, o58.POLICY_NUMBER p2, o62.CALCULATION_DATE p3, '' 
FROM OPERATION_TAX_DETAILS o8 
INNER JOIN BENEFIT_PAYMENT o56 ON o8.OWNER_OID = o56.OID 
INNER JOIN BENEFIT_FILE o57 ON o56.BENEFIT_FILE_OID = o57.OID 
INNER JOIN (POLICY o58 
LEFT OUTER JOIN PENSION_POLICY ql_o58_3 ON o58.OID = ql_o58_3.OID AND o58.VERSION = ql_o58_3.VERSION) ON (o58.POLICY_NUMBER = o57.ORIGIN_IDENTIFIER) 
INNER JOIN TAX_FRAMEWORK_LINK o59 ON (o8.TAX_FRAMEWORK_LINK_OID = o59.OID) 
INNER JOIN BENEFIT_PAYMENT o60 ON o8.OWNER_OID = o60.OID 
INNER JOIN BENEFIT_FILE o61 ON o60.BENEFIT_FILE_OID = o61.OID 
INNER JOIN OPE_TAX_CALCULATION_RESULT o62 ON o62.TAX_RESULT_OWNER_ OID = o8.OID 
WHERE o58.POLICY_NUMBER LIKE :38 AND o59.TAX_FRAMEWORK_ID IS NOT NULL AND o61.ORIGIN_TYPE = :39 
UNION ALL SELECT DISTINCT o9.CID p0, o9.OID p1, - 1, o66.POLICY_NUMBER p2, o70.CALCULATION_DATE p3, '' 
FROM OPERATION_TAX_DETAILS o9 INNER JOIN BENEFIT_PAYMENT o63 ON o9.OWNER_OID = o63.OID 
INNER JOIN BENEFIT_FILE o64 ON o63.BENEFIT_FILE_OID = o64.OID 
INNER JOIN PRODUCT_COMPONENT_IMPL o65 ON (o65.PRODUCT_COMPONENT_NUMBER = o64.ORIGIN_IDENTIFIER) 
INNER JOIN (POLICY o66 LEFT OUTER JOIN PENSION_POLICY ql_o66_3 ON o66.OID = ql_o66_3.OID AND o66.VERSION = ql_o66_3.VERSION) ON o65.POLICY_IMPL_OID = o66.OID 
INNER JOIN TAX_FRAMEWORK_LINK o67 ON (o9.TAX_FRAMEWORK_LINK_OID = o67.OID) 
INNER JOIN BENEFIT_PAYMENT o68 ON o9.OWNER_OID = o68.OID 
INNER JOIN BENEFIT_FILE o69 ON o68.BENEFIT_FILE_OID = o69.OID
INNER JOIN OPE_TAX_CALCULATION_RESULT o70 ON o70.TAX_RESULT_OWNER_OID = o9.OID 
WHERE o66.POLICY_NUMBER LIKE :40 AND o67.TAX_FRAMEWORK_ID IS NOT NULL AND o69.ORIGIN_TYPE = :41;